name: Build and deploy an app to AKS with Helm
on:
    push:
      branches: ["master"]
    workflow_dispatch:
jobs:
    checkout-code:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Check for changes in Chart.yaml
          id: check_changes
          run: |
            if git diff --exit-code HEAD^ HEAD -- Chart.yaml; then
                echo "No changes in Chart.yaml"
                echo "changes=false" >> $GITHUB_ENV
            else
                echo "Changes detected in Chart.yaml"
                echo "changes=true" >> $GITHUB_ENV
            fi
      
        - name: Conditional step based on Chart.yaml changes
          if: env.changes == 'true'
          run: echo "Performing actions because Chart.yaml has changed"