name: Build and deploy an app to AKS with Helm
on:
    push:
      branches: ["master"]
    workflow_dispatch:
jobs:
    checkout-code:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Check for changes in Chart.yaml
          id: check_changes
          run: |
            PREV_SHA=${{ github.event.before }}
            CURR_SHA=${{ github.sha }}
            if git diff --exit-code $PREV_SHA $CURR_SHA -- Chart.yaml; then
                echo "No changes in Chart.yaml"
                echo "changes=false" >> $GITHUB_ENV
            else
                echo "Changes detected in Chart.yaml"
                echo "changes=true" >> $GITHUB_ENV
            fi
      
        - name: Conditional step based on Chart.yaml changes
          if: env.changes == 'true'
          run: echo "Performing actions because Chart.yaml has changed"
        - name: install helm
          run: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh

        - name: validate helm chart
          run: helm lint .
        - name: test helm chart
          run: helm template . -f values.yaml
